name: Deploy dev network
# Builds new binary and deploy on dev network on a new version only.
# A version is denoted with a protected tag.
on:
  push:
    # Only tags which match the protected tag pattern will trigger this workflow
    tags:
      - v*.*.*

env:
  ARTIFACT_BIN: "nolus.tar.gz"
  ARTIFACT_SCRIPTS: "scripts.tar.gz"
  IMAGE_NAME: "public.ecr.aws/nolus/node"
  VERSION_TAG: ${{ github.ref_name }}
  IMAGE_DOCKERFILE: "./build/builder_spec.Dockerfile"
  ACCOUNTS_DIR: "accounts"
  CONTRACTS_INFO_FILE: "contracts-info.json"
  CONTRACTS_REPO: "github.com/Nolus-Protocol/nolus-money-market"
  SMART_CONTRACTS_ADMIN_ADDR: "nolus15jv5h5wjf3haljzfk5vcxx86n33rswsm7u3jgn" 
  FAUCET_TOKENS_DEV: "1000000000000$NLS_DENOM,1000000000000$STABLE_BANK_SYMBOL_DEV"
  STABLE_TICKER_DEV: "USDC"
  CONTRACTS_VERSION: "v0.2.9"
  CONTRACTS_ZIP: "artifacts.zip"
  CONTRACTS_DIR: "artifacts"
 
jobs:
  # Using gh cli to download artifacts from 'nolus-money-market' repo.
  # https://cli.github.com/manual
  download-wasm:
    name: Download wasm contracts
    runs-on: ubuntu-latest
    
    env: 
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: List Releases
        run: | 
          gh release list --repo $CONTRACTS_REPO
      
      - name: Download wasm
        run: |
          gh release download --repo $CONTRACTS_REPO $CONTRACTS_VERSION

      - name: Unzip Contracts Artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.CONTRACTS_ZIP }} -d ${{ env.CONTRACTS_DIR }}


      - name: Archive wasm
        uses: actions/upload-artifact@v3
        with:
          name: wasm-${{ env.CONTRACTS_VERSION }}
          path: ${{ env.CONTRACTS_DIR }}

  # Deploy a new version of the dev network.
  setup-dev-network:
    name: Setup dev network
    runs-on: ubuntu-latest
    needs: [download-wasm]
    container: amazon/aws-cli
    environment: dev chain

    steps:
      - name: Download wasm
        uses: actions/download-artifact@v3
        with:
          name: wasm-${{ env.CONTRACTS_VERSION }}

      - run: |
          ls -lah
          cd $CONTRACTS_DIR
          
          ls -lah