name: Deploy dev network
on:
  push:
    # Only tags which match the protected tag pattern will trigger this workflow
    tags:
      - v*.*.*
jobs:
  download-wasm:
    name: Download wasm contracts
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: wasm
        run: |
          mkdir optimized-binaries-main-net
          mkdir optimized-binaries-test-net
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-main-net/t1.wasm
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-main-net/t2.wasm
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-main-net/t3.wasm
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-test-net/t14.wasm
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-test-net/t24.wasm
          echo "asfsgfdhdfhfdhdfhfdh" >> optimized-binaries-test-net/t34.wasm

      - name: Zip test
        uses: montudor/action-zip@v1
        with:
          args: zip -j -r optimized-binaries-test-net.zip optimized-binaries-test-net/*

      - name: Zip main
        uses: montudor/action-zip@v1
        with:
          args: zip -j -r optimized-binaries-main-net.zip optimized-binaries-main-net/*

      - uses: "marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            optimized-binaries-test-net.zip
            optimized-binaries-main-net.zip
